INFO     testcases.test_pair_api:test_pair_api.py:41 解除配对
DEBUG    urllib3.util.retry:retry.py:351 Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=None, status=None)
DEBUG    urllib3.util.retry:retry.py:351 Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=None, status=None)
DEBUG    urllib3.connectionpool:connectionpool.py:228 Starting new HTTP connection (1): 127.0.0.1:9006
DEBUG    urllib3.connectionpool:connectionpool.py:456 http://127.0.0.1:9006 "POST /api/pair/break HTTP/1.1" 200 40
INFO     testcases.test_pair_api:test_pair_api.py:43 {'code': 0, 'data': {'state': 0}, 'msg': 'ok'}